# Generated by Django 4.0.4 on 2022-05-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Váriavel', 'verbose_name_plural': 'Variações'},
        ),
    ]
